#! /usr/bin/env bash
REPOTAR=repo.$(date +%Y%m%d%H%M%S).tar.gz
echo "Saving repository into local file $REPOTAR ..."
docker exec heroes_persistence_1 tar -czf $REPOTAR /opt/testeditor/repo || exit 1
docker cp heroes_persistence_1\:/opt/testeditor/$REPOTAR . || exit 1
docker exec heroes_persistence_1 rm $REPOTAR || exit 1
echo "Finished saving repository into local file $REPOTAR"
