#! /usr/bin/env bash
echo "Stopping test-editor-web ..."
if [ -f "local_env.rc" ]; then set -o allexport; source local_env.rc; set +o allexport; fi
# make sure old test runs do not interfere with next startup
docker exec heroes_testexecution_1 find /workdir/repo -type f -regex ".*/logs/.*\(log\|yaml\)" -exec rm {} \;
docker exec heroes_testexecution_1 find /workdir/repo -type f -regex ".*/screenshots/.*" -exec rm {} \;
docker exec heroes_testexecution_1 find /workdir/repo -type f -regex ".*/\.testexecution/.*" -exec rm {} \;
docker-compose stop
echo "Stopped test-editor-web."
