#!/bin/bash
echo "Starting tutorial Hero Crete Specification."
echo
echo "If unresponse for too long (> 30 seconds), abort by pressing ctrl-c."
sleep 2

BRANCH=hero-create-specification docker-compose up > te.log &
CNT=0
TCNT=0
echo "Waiting for the test-editor-web components to download ..."
tail -f te.log | while read LOGLINE
do
   TCNT=$((TCNT+1))
   CNT=$((CNT+1))
   if [ "$TCNT" -eq 1 ]; then
     echo "Starting up backends (initialize java, dropwizard, gradle) ..."
   fi
   if [ "$CNT" -eq 1 ]; then
      echo -n "  ."
   else
      echo -n "."
   fi
   if [ "$CNT" -gt 35 ]; then CNT=0; echo ""; fi
   echo $LOGLINE | grep -q -e "xtext_1.*INFO.*org.eclipse.jetty.server.Server: Started @.*ms" && pkill -P $$ tail
done
echo ""
echo "Backends initialized."
echo -n "Starting "

FIREFOX=$(which firefox 2> /dev/null)
CHROME=$(which chrome 2> /dev/null)
CHROMIUM=$(which chromium-browser 2> /dev/null)

if [ "$FIREFOX" != "" ]; then
  echo "firefox ..."
  $FIREFOX http://localhost:4200
elif [ "$CHROMIUM" != "" ]; then
  echo "chromium ..."
  $CHROMIUM http://localhost:4200
elif [ "$CHROME" != "" ]; then
  echo "firefox ..."
  $CHROME http://localhost:4200
else
  echo "browser failed."
  echo "No valid browser found."
fi
